androidapp/DansFrappesRaps/app/build.gradle
androidapp/DansFrappesRaps/app/google-services.json
androidapp/DansFrappesRaps/build.gradle

Making the dependencies and files for firebase

36 firebase init

---

androidapp/DansFrappesRaps/app/build.gradle

Forgot to include this dependency when I made the first PR!
Allows firebase actions to be used through coroutines
closes #36

36 coroutine support for firebase

---

androidapp/DansFrappesRaps/app/build.gradle
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/MainActivity.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignTextInput.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/MenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignInScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SignInViewModel.kt
androidapp/DansFrappesRaps/build.gradle

Closes #49 
Adding the login screen and firebase hookups
updating kotlin version to allow for use with firebase

49 kyle high fidelity prototype

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignUpScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SignUpViewModel.kt

Creating the sign up screen template based on CS3200!

Adjusting navigation for new sign up screen, adding signup screen, viewmodel

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignButton.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignTextInput.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignInScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignUpScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SignUpViewModel.kt

Updating sign up and sign in to match figma designs
adjusting the scaffold component to display the correct top bar
Closes #83

83 Sign up and in screen UI

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignButton.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignTextInput.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/MenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignUpScreen.kt

Update sign up and aign in screens with material3 libraries

Material3 changes

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignTextInput.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/User.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignUpScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SignUpViewModel.kt

Adding database user creation upon signup
Fixing typing bug on sign up screen
Switching email and name fields on signup

84 kyle sign up database 

---

androidapp/DansFrappesRaps/app/build.gradle
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/RootNavigationViewModel.kt

47 kyle scaffold composable

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SplashScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SplashScreenViewModel.kt

splash screen and auto login

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/MenuItem.kt
androidapp/DansFrappesRaps/app/src/main/res/drawable/emptyimage.xml

Generic Menu Item. Need to change defaults
parameters:
name:String 
imageId: Int
imageDescription: String

113 create menuitem component

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt

Added floating action button
Created #132

Add floating action button

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/RootNavigationViewModel.kt

Fixing the bug that made the side menu only work when signing in with the sign in screen, now allows auto sign in 
closes #132

making auto sign in correctly work with side menu

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/OrderItem.kt

Composable for Order Item
TODO: Onclick activity
Default size is static, change to dynamic

order item ui

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/InventoryItem.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Inventory.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/IngredientsRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/InventoryRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/AdjustInventoryScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/AdjustInventoryViewModel.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditMenuViewModel.kt

Adding type to inventories
closes #156

Adding item type to inventories

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/UserListItem.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/User.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/DetailMenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EditUserScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditUserViewModel.kt

Adding hours and payrate to employee users

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EditUserProfileScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ProfileScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditUserProfileViewModel.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/ProfileScreenViewModel.kt

adding profile screen support for customer and employee/manager

 profile screen

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/LabelledTextInput.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/Loader.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/DetailMenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/DetailMenuViewModel.kt

UI still looks off. Make a new issue to address it.

160 create view model detailmenuscreen

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/ManagePayrollItem.kt

Making item auto close

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Inventory.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/InventoryRepository.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/AdjustInventoryScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/AdjustInventoryViewModel.kt

adding isCountable flag

---

androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/DrinkItem.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/IngredientItem.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/DetailMenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/MenuScreen.kt
androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/DetailMenuViewModel.kt

174 improve UI
